
file(READ "${PROJECT_SOURCE_DIR}/src/core/cpp/include/drpc.hpp" _DRPC_H_CONTENTS)
string(REGEX REPLACE ".*#define DRPC_VERSION_MAJOR ([0-9]+).*" "\\1" DRPC_VERSION_MAJOR "${_DRPC_H_CONTENTS}")
string(REGEX REPLACE ".*#define DRPC_VERSION_MINOR ([0-9]+).*" "\\1" DRPC_VERSION_MINOR "${_DRPC_H_CONTENTS}")
string(REGEX REPLACE ".*#define DRPC_VERSION_PATCH ([0-9]+).*" "\\1" DRPC_VERSION_PATCH "${_DRPC_H_CONTENTS}")
set(DRPC_VERSION "${DRPC_VERSION_MAJOR}.${DRPC_VERSION_MINOR}.${DRPC_VERSION_PATCH}")

message(STATUS "Detected DRPC Version - ${DRPC_VERSION}")
